name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifier le code source
    - name: Checkout repository
      uses: actions/checkout@v3

      # 2. Déconnexion de Docker pour réinitialiser l'accès
    - name: Docker logout
      run: docker logout ghcr.io

    # 3. Connexion à GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 4. Construire l'image Docker
    - name: Build Docker image
      run: docker build -t ghcr.io/honoflame-school/jokesapp:latest .

      # 5. Lister les images Docker disponibles pour vérifier la présence de l'image
    - name: List Docker images
      run: docker images

    # 6. Scanner l'image Docker avec Trivy
    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@0.29.0  # Utilisation de la version v0.29.0
      with:
        image-ref: ghcr.io/honoflame-school/jokesapp:latest

    # 7. Pousser l'image vers GitHub Container Registry
    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/honoflame-school/jokesapp:latest
